[flavor]
dark = "catppuccin-mocha"

[git]
unknown_sign = ""
modified_sign = "!"
added_sign = "+"
untracked_sign = "?"
ignored_sign = ""
deleted_sign = "✘"
updated_sign = "~"
clean_sign = " "

unknown = {}
modified = { fg = "yellow", bold = true }
added = { fg = "green", bold = true }
untracked = { fg = "yellow", dim = true }
ignored = {}
deleted = { fg = "red", bold = true }
updated = {}
clean = {}
